# Generated by Django 5.0.6 on 2024-06-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_image',
            new_name='product_image',
        ),
    ]
