# Generated by Django 5.0.6 on 2024-06-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_profile_image_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='product_price',
        ),
    ]
